### ISSUE TITLE
Can't remove aspCouponSpinner

### ISSUE THREAD

**Issue by mitsunobuk** [Arsenal21/stripe-payments#111]
When I use coupon, `<div class="asp-spinner">Loading...</div>` can't be removed.
If I remove
`stripehandler.updateAllAmounts(data); `
in stripe-handler.js 491. It's going well.

Does it make any problem?
I use legacy checkout.

**Comment by erommel** [comment]
Hi.

If you're having issues with spinner display (e.g. "Loading..." is displayed instead of spinner), this means there are some issues with CSS on page.

Removing any JavaScript code is a bad idea, especially the part that updates amounts ;-)

Please contact us via this form https://s-plugins.com/contact-us/ and send your website URL along with short description what you want to achieve. We will try to assist you with this

**Comment by mitsunobuk** [comment]
To Alexander C,

Thanks your comment. I gave you a contact via s-plugin.com. 

What it happen is when user apply coupon, .asp-spinner is spinning. Then it's supposed to be removed. But it never been ended.

Check my conatact. If you have any idea, please advise me.

Regards

**Comment by erommel** [comment]
Let's handle this via email. It doesn't seem to be a bug of core plugin, but rather custom code issues.

Closing this issue.

**Comment by mitsunobuk** [comment]
I made a mistake. I should put decimals in Price Display Settings.

Thanks your help.
