### ISSUE TITLE
Looks like Stripe PHP lib is going to drop support of older PHP versions

### ISSUE THREAD

**Issue by erommel** [Arsenal21/stripe-payments#64]
At the moment, it looks like they're going to drop PHP 5.4 and 5.5. soon: https://github.com/stripe/stripe-php/pull/552

We're currently using older Stripe lib which is PHP 5.3 compatible. However, for new features (like webhooks API etc) we gonna need to update it to the latest lib version, which requires PHP 5.4 at least.

Since it appears some of our customers are still using PHP <=5.3, we need to add a notice for them to upgrade their PHP to 5.4 at least.

**Comment by erommel** [comment]
I have created a new branch and will try to play around with new Stripe Lib there: https://github.com/Arsenal21/stripe-payments/tree/testing

**Comment by appthemes7** [comment]
Its totally okay to up the minimum requirement to PHP5.4 or 5.5. When we release the new version with PHP5.4 as the minimum requirment, We will have a BIG notice in the "Change Log" that mentions this. So that should take care of it (since it is a very small portion of users who use older than PHP5.4).

**Comment by Arsenal21** [comment]
Its totally okay to up the minimum requirement to PHP5.4 or 5.5. When we release the new version with PHP5.4 as the minimum requirment, We will have a BIG notice in the "Change Log" that mentions this. So that should take care of it (since it is a very small portion of users who use older than PHP5.4).

**Comment by erommel** [comment]
This is handled for now. Closing it to reopen when it's time to drop PHP 5.4 support.
